<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Frequência';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php if (isset($mensagem)) : ?>
    		<div class="alert alert-warning">
    			<?php echo $mensagem ?>
    			<button type="button" class="close" data-dismiss="alert">×</button>
    		</div>
    	<?php endif;
    	$form = $this->form;
		$form->setAttribute('action', $this->url('frequencia/default', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idfrequencia')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('funcionariofuncionario'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('funcionariofuncionario')) ?>
				<?php echo $this->formElementErrors($form->get('funcionariofuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script>
jQuery(function($){
   $("#horarioentrada").mask("99:99");
   $("#horariosaida").mask("99:99");
});
</script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
<script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
<script>
$(function() {
    $( "#dataFrequencia" ).datepicker({dateFormat: 'dd/mm/yy'});
});
</script>


