<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Frequência';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('frequencia', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idfrequencia')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('horarioentrada'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('horarioentrada')) ?>
				<?php echo $this->formElementErrors($form->get('horarioentrada')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('horariosaida'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('horariosaida')) ?>
				<?php echo $this->formElementErrors($form->get('horariosaida')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('funcionariofuncionario'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('funcionariofuncionario')) ?>
				<?php echo $this->formElementErrors($form->get('funcionariofuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('dataFrequencia'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('dataFrequencia')) ?>
				<?php echo $this->formElementErrors($form->get('dataFrequencia')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script>
jQuery(function($){
   $("#horarioentrada").mask("99:99");
   $("#horariosaida").mask("99:99");
   $("#dataFrequencia").mask("99/99/9999");
});
</script>