<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Frequências';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('frequencia', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Frequência</a>
            <a class="btn btn-warning" href="#"><span class="glyphicon glyphicon-eye-open"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <thead>
            <th>Funcionário</th>
            <th>Data</th>
            <th>Entrada</th>
            <th>Saída</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($frequencias as $frequencia) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($frequencia->getFuncionariofuncionario()->getNomefuncionario());?></td>
            <td><?php echo $this->escapeHtml($frequencia->getDataFrequencia()->format('d/m/Y'));?></td>
            <td><?php echo $this->escapeHtml($frequencia->getHorarioentrada());?></td>
            <td><?php echo $this->escapeHtml($frequencia->getHorariosaida());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('frequencia',
                    array('action'=>'edit', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('frequencia',
                    array('action'=>'delete', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('frequencia',
                    array('action'=>'view', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>