<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Frequências';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <?php if (isset($mensagem)) : ?>
            <div class="alert alert-warning">
                <?php echo $mensagem ?>
                <button type="button" class="close" data-dismiss="alert">×</button>
            </div>
        <?php endif; ?>
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('frequencia/default', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Frequência</a>
            <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <thead>
            <th>Funcionário</th>
            <th>Data</th>
            <th>Entrada</th>
            <th>Saída</th>
            <th>Presente</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($this->data as $frequencia) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($frequencia->getFuncionariofuncionario()->getNomefuncionario());?></td>
            <td><?php echo $this->escapeHtml($frequencia->getHorarioentrada()->format('d/m/Y'));?></td>
            <td><?php echo $this->escapeHtml($frequencia->getHorarioentrada()->format('H:i:s'));?></td>
            <td><?php echo $this->escapeHtml($frequencia->getHorariosaida() == NULL ? '-' : $frequencia->getHorariosaida()->format('H:i:s'));?></td>
            <td><?php echo $this->escapeHtml($frequencia->getStatusFrequencia()) ? 'Sim' : 'Não'; ?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('frequencia/default',
                    array('action'=>'saida', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-edit"></span> Saída</a>
                <a class="btn btn-danger" href="<?php echo $this->url('frequencia/default',
                    array('action'=>'delete', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('frequencia/default',
                    array('action'=>'view', 'id' => $frequencia->getIdfrequencia()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
        <center>
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'funcionario/paginator')); ?>
        </center>
    </div>
</div>