<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Visitante';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('visitante/default', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idVisitante')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('nomeVisitante'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('nomeVisitante')) ?>
				<?php echo $this->formElementErrors($form->get('nomeVisitante')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('profissaoVisitante'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('profissaoVisitante')) ?>
				<?php echo $this->formElementErrors($form->get('profissaoVisitante')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('instituicaoVisitante'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('instituicaoVisitante')) ?>
				<?php echo $this->formElementErrors($form->get('instituicaoVisitante')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('objetivoVisitante'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('objetivoVisitante')) ?>
				<?php echo $this->formElementErrors($form->get('objetivoVisitante')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
