<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Visitantes';
    $this->headTitle($title);

    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <a class="btn btn-success" href="<?php echo $this->url('visitante/default', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Visitante</a>
        
        <a class="btn btn-default" href="<?php echo $this->url('visitante/default', array('action'=>'relatorio'));?>"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>

        <table class="table">
        <thead>
            <th>Nome</th>
            <th>Profissão</th>
            <th>Instituição</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($this->data as $visitante) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($visitante->getNomeVisitante());?></td>
            <td><?php echo $this->escapeHtml($visitante->getProfissaoVisitante());?></td>
            <td><?php echo $this->escapeHtml($visitante->getInstituicaoVisitante());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('visitante/default',
                    array('action'=>'edit', 'id' => $visitante->getIdVisitante()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('visitante/default',
                    array('action'=>'delete', 'id' => $visitante->getIdVisitante()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('visitante/default',
                    array('action'=>'view', 'id' => $visitante->getIdVisitante()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
        <center>
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'visitante/paginator')); ?>
        </center>
    </div>
</div>