<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			
			$title = 'Visitante '. $visitante->getNomeVisitante();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Id</strong></td>
			    		<td><?php echo $visitante->getIdVisitante(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $visitante->getNomeVisitante(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Profissão</strong></td>
			    		<td><?php echo $visitante->getProfissaoVisitante(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Instituição</strong></td>
			    		<td><?php echo $visitante->getInstituicaoVisitante(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Objetivo</strong></td>
			    		<td><?php echo $visitante->getObjetivoVisitante(); ?></td>
			    	</tr>
			    </table>
			</div>
		</div>
		<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
		<a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
	</div>
</div>
