<?php

namespace DoctrineORMModule\Proxy\__CG__\Professor\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Departamento extends \Professor\Entity\Departamento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'iddepartamento', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'nomedepartamento', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'descricaodepartamento', 'professordepartamento');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'iddepartamento', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'nomedepartamento', '' . "\0" . 'Professor\\Entity\\Departamento' . "\0" . 'descricaodepartamento', 'professordepartamento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Departamento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIddepartamento()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIddepartamento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddepartamento', array());

        return parent::getIddepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomedepartamento($nomedepartamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomedepartamento', array($nomedepartamento));

        return parent::setNomedepartamento($nomedepartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomedepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomedepartamento', array());

        return parent::getNomedepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricaodepartamento($descricaodepartamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricaodepartamento', array($descricaodepartamento));

        return parent::setDescricaodepartamento($descricaodepartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricaodepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricaodepartamento', array());

        return parent::getDescricaodepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessorDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessorDepartamento', array());

        return parent::getProfessorDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
