<?php

namespace DoctrineORMModule\Proxy\__CG__\Sala\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ReservaSala extends \Sala\Entity\ReservaSala implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdreservasala()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idreservasala"];
        }
        $this->__load();
        return parent::getIdreservasala();
    }

    public function setObjetivo($objetivo)
    {
        $this->__load();
        return parent::setObjetivo($objetivo);
    }

    public function getObjetivo()
    {
        $this->__load();
        return parent::getObjetivo();
    }

    public function setDatainicio($datainicio)
    {
        $this->__load();
        return parent::setDatainicio($datainicio);
    }

    public function getDatainicio()
    {
        $this->__load();
        return parent::getDatainicio();
    }

    public function setDatafim($datafim)
    {
        $this->__load();
        return parent::setDatafim($datafim);
    }

    public function getDatafim()
    {
        $this->__load();
        return parent::getDatafim();
    }

    public function setSalasala(\Sala\Entity\Sala $salasala = NULL)
    {
        $this->__load();
        return parent::setSalasala($salasala);
    }

    public function getSalasala()
    {
        $this->__load();
        return parent::getSalasala();
    }

    public function setProfessorprofessor(\Professor\Entity\Professor $professorprofessor = NULL)
    {
        $this->__load();
        return parent::setProfessorprofessor($professorprofessor);
    }

    public function getProfessorprofessor()
    {
        $this->__load();
        return parent::getProfessorprofessor();
    }

    public function setFuncionariofuncionario(\Funcionario\Entity\Funcionario $funcionariofuncionario = NULL)
    {
        $this->__load();
        return parent::setFuncionariofuncionario($funcionariofuncionario);
    }

    public function getFuncionariofuncionario()
    {
        $this->__load();
        return parent::getFuncionariofuncionario();
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }

    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idreservasala', 'objetivo', 'datainicio', 'datafim', 'salasala', 'professorprofessor', 'funcionariofuncionario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}