<?php

namespace DoctrineORMModule\Proxy\__CG__\Funcionario\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Funcionario extends \Funcionario\Entity\Funcionario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdfuncionario()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idfuncionario"];
        }
        $this->__load();
        return parent::getIdfuncionario();
    }

    public function setNomefuncionario($nomefuncionario)
    {
        $this->__load();
        return parent::setNomefuncionario($nomefuncionario);
    }

    public function getNomefuncionario()
    {
        $this->__load();
        return parent::getNomefuncionario();
    }

    public function setEmailfuncionario($emailfuncionario)
    {
        $this->__load();
        return parent::setEmailfuncionario($emailfuncionario);
    }

    public function getEmailfuncionario()
    {
        $this->__load();
        return parent::getEmailfuncionario();
    }

    public function setTelefonefuncionario($telefonefuncionario)
    {
        $this->__load();
        return parent::setTelefonefuncionario($telefonefuncionario);
    }

    public function getTelefonefuncionario()
    {
        $this->__load();
        return parent::getTelefonefuncionario();
    }

    public function setDatanasc($datanasc)
    {
        $this->__load();
        return parent::setDatanasc($datanasc);
    }

    public function getDatanasc()
    {
        $this->__load();
        return parent::getDatanasc();
    }

    public function setDataAdmissao($dataAdmissao)
    {
        $this->__load();
        return parent::setDataAdmissao($dataAdmissao);
    }

    public function getDataAdmissao()
    {
        $this->__load();
        return parent::getDataAdmissao();
    }

    public function getProjetoprojeto()
    {
        $this->__load();
        return parent::getProjetoprojeto();
    }

    public function setGrauInstrucao($grauInstrucao)
    {
        $this->__load();
        return parent::setGrauInstrucao($grauInstrucao);
    }

    public function getGrauInstrucao()
    {
        $this->__load();
        return parent::getGrauInstrucao();
    }

    public function setFormacao($formacao)
    {
        $this->__load();
        return parent::setFormacao($formacao);
    }

    public function getFormacao()
    {
        $this->__load();
        return parent::getFormacao();
    }

    public function setFuncao($funcao)
    {
        $this->__load();
        return parent::setFuncao($funcao);
    }

    public function getFuncao()
    {
        $this->__load();
        return parent::getFuncao();
    }

    public function setHorarioInicio($horarioInicio)
    {
        $this->__load();
        return parent::setHorarioInicio($horarioInicio);
    }

    public function getHorarioInicio()
    {
        $this->__load();
        return parent::getHorarioInicio();
    }

    public function setHorarioFim($horarioFim)
    {
        $this->__load();
        return parent::setHorarioFim($horarioFim);
    }

    public function getHorarioFim()
    {
        $this->__load();
        return parent::getHorarioFim();
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }

    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idfuncionario', 'nomefuncionario', 'emailfuncionario', 'telefonefuncionario', 'datanasc', 'dataAdmissao', 'grauInstrucao', 'formacao', 'funcao', 'horarioInicio', 'horarioFim');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}