<?php

namespace DoctrineORMModule\Proxy\__CG__\Sala\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ReservaSala extends \Sala\Entity\ReservaSala implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdReservaSala()
    {
        $this->__load();
        return parent::getIdReservaSala();
    }

    public function setObjetivo($objetivo)
    {
        $this->__load();
        return parent::setObjetivo($objetivo);
    }

    public function getObjetivo()
    {
        $this->__load();
        return parent::getObjetivo();
    }

    public function setDataInicio($dataInicio)
    {
        $this->__load();
        return parent::setDataInicio($dataInicio);
    }

    public function getDataInicio()
    {
        $this->__load();
        return parent::getDataInicio();
    }

    public function setDataFim($dataFim)
    {
        $this->__load();
        return parent::setDataFim($dataFim);
    }

    public function getDataFim()
    {
        $this->__load();
        return parent::getDataFim();
    }

    public function setDataReserva($dataReserva)
    {
        $this->__load();
        return parent::setDataReserva($dataReserva);
    }

    public function getDataReserva()
    {
        $this->__load();
        return parent::getDataReserva();
    }

    public function setSalaReserva(\Sala\Entity\Sala $salaReserva = NULL)
    {
        $this->__load();
        return parent::setSalaReserva($salaReserva);
    }

    public function getSalaReserva()
    {
        $this->__load();
        return parent::getSalaReserva();
    }

    public function setFuncionarioReserva(\Funcionario\Entity\Funcionario $funcionarioReserva = NULL)
    {
        $this->__load();
        return parent::setFuncionarioReserva($funcionarioReserva);
    }

    public function getFuncionarioReserva()
    {
        $this->__load();
        return parent::getFuncionarioReserva();
    }

    public function setProfessorReserva(\Professor\Entity\Professor $professorReserva = NULL)
    {
        $this->__load();
        return parent::setProfessorReserva($professorReserva);
    }

    public function getProfessorReserva()
    {
        $this->__load();
        return parent::getProfessorReserva();
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }

    public function populate($data = array (
))
    {
        $this->__load();
        return parent::populate($data);
    }

    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {
        $this->__load();
        return parent::setInputFilter($inputFilter);
    }

    public function getInputFilter()
    {
        $this->__load();
        return parent::getInputFilter();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idreservaSala', 'objetivo', 'dataInicio', 'dataFim', 'dataReserva', 'salaReserva', 'professorReserva', 'funcionarioReserva');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}