<?php

namespace DoctrineORMModule\Proxy\__CG__\Professor\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Professor extends \Professor\Entity\Professor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'inputFilter', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'idprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'matriculaprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'nomeprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'emailprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'telefoneprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'areadeatuacao', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'cursoProfessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'titulacao', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'classe', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'regimedetrabalho', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'tipovinculo', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'datanasc', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'professorprojeto', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'departamentodepartamento', 'professorCoordProjeto');
        }

        return array('__isInitialized__', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'inputFilter', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'idprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'matriculaprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'nomeprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'emailprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'telefoneprofessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'areadeatuacao', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'cursoProfessor', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'titulacao', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'classe', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'regimedetrabalho', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'tipovinculo', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'datanasc', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'professorprojeto', '' . "\0" . 'Professor\\Entity\\Professor' . "\0" . 'departamentodepartamento', 'professorCoordProjeto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Professor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdprofessor()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdprofessor();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprofessor', array());

        return parent::getIdprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaprofessor($matriculaprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaprofessor', array($matriculaprofessor));

        return parent::setMatriculaprofessor($matriculaprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessorCoordProjeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessorCoordProjeto', array());

        return parent::getProfessorCoordProjeto();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaprofessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaprofessor', array());

        return parent::getMatriculaprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeprofessor($nomeprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeprofessor', array($nomeprofessor));

        return parent::setNomeprofessor($nomeprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeprofessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeprofessor', array());

        return parent::getNomeprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailprofessor($emailprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailprofessor', array($emailprofessor));

        return parent::setEmailprofessor($emailprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailprofessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailprofessor', array());

        return parent::getEmailprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneprofessor($telefoneprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneprofessor', array($telefoneprofessor));

        return parent::setTelefoneprofessor($telefoneprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneprofessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneprofessor', array());

        return parent::getTelefoneprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreadeatuacao($areadeatuacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreadeatuacao', array($areadeatuacao));

        return parent::setAreadeatuacao($areadeatuacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreadeatuacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreadeatuacao', array());

        return parent::getAreadeatuacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacao($formacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacao', array($formacao));

        return parent::setFormacao($formacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacao', array());

        return parent::getFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulacao($titulacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulacao', array($titulacao));

        return parent::setTitulacao($titulacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulacao', array());

        return parent::getTitulacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', array($classe));

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', array());

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegimedetrabalho($regimedetrabalho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegimedetrabalho', array($regimedetrabalho));

        return parent::setRegimedetrabalho($regimedetrabalho);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegimedetrabalho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegimedetrabalho', array());

        return parent::getRegimedetrabalho();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipovinculo($tipovinculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipovinculo', array($tipovinculo));

        return parent::setTipovinculo($tipovinculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipovinculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipovinculo', array());

        return parent::getTipovinculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatanasc($datanasc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatanasc', array($datanasc));

        return parent::setDatanasc($datanasc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatanasc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatanasc', array());

        return parent::getDatanasc();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjetoprojeto(\Projeto\Entity\Projeto $professorprojeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjetoprojeto', array($professorprojeto));

        return parent::addProjetoprojeto($professorprojeto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjetoprojeto(\Projeto\Entity\Projeto $professorprojeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjetoprojeto', array($professorprojeto));

        return parent::removeProjetoprojeto($professorprojeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetoprojeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetoprojeto', array());

        return parent::getProjetoprojeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamentodepartamento(\Professor\Entity\Departamento $departamentodepartamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamentodepartamento', array($departamentodepartamento));

        return parent::setDepartamentodepartamento($departamentodepartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamentodepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamentodepartamento', array());

        return parent::getDepartamentodepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoProfessor(\Curso\Entity\Curso $cursoProfessor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoProfessor', array($cursoProfessor));

        return parent::setCursoProfessor($cursoProfessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoProfessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoProfessor', array());

        return parent::getCursoProfessor();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
