<?php

namespace DoctrineORMModule\Proxy\__CG__\Equipamento\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipamento extends \Equipamento\Entity\Equipamento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'idequipamento', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'ntombo', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'observacao', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'tipoequipamentotipoequipamento', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'salasala', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'projetoprojeto', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'tombotombo');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'idequipamento', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'ntombo', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'observacao', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'tipoequipamentotipoequipamento', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'salasala', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'projetoprojeto', '' . "\0" . 'Equipamento\\Entity\\Equipamento' . "\0" . 'tombotombo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipamento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addTombotombo(\Equipamento\Entity\Tombo $tombotombo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTombotombo', array($tombotombo));

        return parent::addTombotombo($tombotombo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTombotombo(\Equipamento\Entity\Tombo $tombotombo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTombotombo', array($tombotombo));

        return parent::removeTombotombo($tombotombo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTombotombo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTombotombo', array());

        return parent::getTombotombo();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdequipamento()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdequipamento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdequipamento', array());

        return parent::getIdequipamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNtombo($ntombo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNtombo', array($ntombo));

        return parent::setNtombo($ntombo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNtombo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNtombo', array());

        return parent::getNtombo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoequipamentotipoequipamento(\Equipamento\Entity\TipoEquipamento $tipoequipamentotipoequipamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoequipamentotipoequipamento', array($tipoequipamentotipoequipamento));

        return parent::setTipoequipamentotipoequipamento($tipoequipamentotipoequipamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoequipamentotipoequipamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoequipamentotipoequipamento', array());

        return parent::getTipoequipamentotipoequipamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalasala(\Sala\Entity\Sala $salasala = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalasala', array($salasala));

        return parent::setSalasala($salasala);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalasala()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalasala', array());

        return parent::getSalasala();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjetoprojeto(\Projeto\Entity\Projeto $projetoprojeto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjetoprojeto', array($projetoprojeto));

        return parent::setProjetoprojeto($projetoprojeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetoprojeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetoprojeto', array());

        return parent::getProjetoprojeto();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
