<?php

namespace DoctrineORMModule\Proxy\__CG__\Aluno\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aluno extends \Aluno\Entity\Aluno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'idaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'nomealuno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'emailaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'telefonealuno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'matriculaaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'cursoAluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'bolsista', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'datanasc', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'alunoprojeto');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'idaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'nomealuno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'emailaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'telefonealuno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'matriculaaluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'cursoAluno', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'bolsista', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'datanasc', '' . "\0" . 'Aluno\\Entity\\Aluno' . "\0" . 'alunoprojeto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Aluno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdaluno()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdaluno();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdaluno', array());

        return parent::getIdaluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomealuno($nomealuno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomealuno', array($nomealuno));

        return parent::setNomealuno($nomealuno);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomealuno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomealuno', array());

        return parent::getNomealuno();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailaluno($emailaluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailaluno', array($emailaluno));

        return parent::setEmailaluno($emailaluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailaluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailaluno', array());

        return parent::getEmailaluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonealuno($telefonealuno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonealuno', array($telefonealuno));

        return parent::setTelefonealuno($telefonealuno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonealuno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonealuno', array());

        return parent::getTelefonealuno();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaaluno($matriculaaluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaaluno', array($matriculaaluno));

        return parent::setMatriculaaluno($matriculaaluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaaluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaaluno', array());

        return parent::getMatriculaaluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoAluno(\Curso\Entity\Curso $cursoAluno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoAluno', array($cursoAluno));

        return parent::setCursoAluno($cursoAluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoAluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoAluno', array());

        return parent::getCursoAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setBolsista($bolsista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBolsista', array($bolsista));

        return parent::setBolsista($bolsista);
    }

    /**
     * {@inheritDoc}
     */
    public function getBolsista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBolsista', array());

        return parent::getBolsista();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatanasc($datanasc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatanasc', array($datanasc));

        return parent::setDatanasc($datanasc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatanasc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatanasc', array());

        return parent::getDatanasc();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjetoprojeto(\Projeto\Entity\Projeto $alunoprojeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjetoprojeto', array($alunoprojeto));

        return parent::addProjetoprojeto($alunoprojeto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjetoprojeto(\Projeto\Entity\Projeto $alunoprojeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjetoprojeto', array($alunoprojeto));

        return parent::removeProjetoprojeto($alunoprojeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetoprojeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetoprojeto', array());

        return parent::getProjetoprojeto();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
