<?php

namespace DoctrineORMModule\Proxy\__CG__\Projeto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projeto extends \Projeto\Entity\Projeto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'idprojeto', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'titulo', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'objetivogeral', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'objetivoespec', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'resultadosesperados', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'finaciamento', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'tipoPesquisa', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'fontefinaciamento', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'alunoaluno', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'professorprofessor', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'professorcoordenador', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'grupoPesquisaProjeto');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'idprojeto', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'titulo', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'objetivogeral', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'objetivoespec', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'resultadosesperados', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'finaciamento', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'tipoPesquisa', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'fontefinaciamento', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'alunoaluno', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'professorprofessor', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'professorcoordenador', '' . "\0" . 'Projeto\\Entity\\Projeto' . "\0" . 'grupoPesquisaProjeto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projeto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdprojeto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdprojeto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprojeto', array());

        return parent::getIdprojeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivogeral($objetivogeral)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivogeral', array($objetivogeral));

        return parent::setObjetivogeral($objetivogeral);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivogeral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivogeral', array());

        return parent::getObjetivogeral();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivoespec($objetivoespec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivoespec', array($objetivoespec));

        return parent::setObjetivoespec($objetivoespec);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivoespec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivoespec', array());

        return parent::getObjetivoespec();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultadosesperados($resultadosesperados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultadosesperados', array($resultadosesperados));

        return parent::setResultadosesperados($resultadosesperados);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultadosesperados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultadosesperados', array());

        return parent::getResultadosesperados();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinaciamento($finaciamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinaciamento', array($finaciamento));

        return parent::setFinaciamento($finaciamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinaciamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinaciamento', array());

        return parent::getFinaciamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPesquisa($tipoPesquisa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPesquisa', array($tipoPesquisa));

        return parent::setTipoPesquisa($tipoPesquisa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPesquisa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPesquisa', array());

        return parent::getTipoPesquisa();
    }

    /**
     * {@inheritDoc}
     */
    public function setFontefinaciamento($fontefinaciamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFontefinaciamento', array($fontefinaciamento));

        return parent::setFontefinaciamento($fontefinaciamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFontefinaciamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFontefinaciamento', array());

        return parent::getFontefinaciamento();
    }

    /**
     * {@inheritDoc}
     */
    public function addAlunoaluno(\Aluno\Entity\Aluno $alunoaluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlunoaluno', array($alunoaluno));

        return parent::addAlunoaluno($alunoaluno);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlunoaluno(\Aluno\Entity\Aluno $alunoaluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlunoaluno', array($alunoaluno));

        return parent::removeAlunoaluno($alunoaluno);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlunoaluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlunoaluno', array());

        return parent::getAlunoaluno();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfessorprofessor(\Professor\Entity\Professor $professorprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfessorprofessor', array($professorprofessor));

        return parent::addProfessorprofessor($professorprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProfessorprofessor(\Professor\Entity\Professor $professorprofessor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProfessorprofessor', array($professorprofessor));

        return parent::removeProfessorprofessor($professorprofessor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessorprofessor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessorprofessor', array());

        return parent::getProfessorprofessor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessorcoordenador(\Professor\Entity\Professor $professorcoordenador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessorcoordenador', array($professorcoordenador));

        return parent::setProfessorcoordenador($professorcoordenador);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessorcoordenador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessorcoordenador', array());

        return parent::getProfessorcoordenador();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPesquisaProjeto(\Projeto\Entity\GrupoPesquisa $grupoPesquisaProjeto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPesquisaProjeto', array($grupoPesquisaProjeto));

        return parent::setGrupoPesquisaProjeto($grupoPesquisaProjeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPesquisaProjeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPesquisaProjeto', array());

        return parent::getGrupoPesquisaProjeto();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
