<?php

namespace DoctrineORMModule\Proxy\__CG__\Funcionario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Funcionario extends \Funcionario\Entity\Funcionario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'idfuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'nomefuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'emailfuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'telefonefuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'datanasc', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'dataAdmissao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'grauInstrucao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'formacao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'funcao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'horarioInicio', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'horarioFim');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'idfuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'nomefuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'emailfuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'telefonefuncionario', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'datanasc', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'dataAdmissao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'grauInstrucao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'formacao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'funcao', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'horarioInicio', '' . "\0" . 'Funcionario\\Entity\\Funcionario' . "\0" . 'horarioFim');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Funcionario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdfuncionario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdfuncionario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfuncionario', array());

        return parent::getIdfuncionario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomefuncionario($nomefuncionario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomefuncionario', array($nomefuncionario));

        return parent::setNomefuncionario($nomefuncionario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomefuncionario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomefuncionario', array());

        return parent::getNomefuncionario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailfuncionario($emailfuncionario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailfuncionario', array($emailfuncionario));

        return parent::setEmailfuncionario($emailfuncionario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailfuncionario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailfuncionario', array());

        return parent::getEmailfuncionario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonefuncionario($telefonefuncionario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonefuncionario', array($telefonefuncionario));

        return parent::setTelefonefuncionario($telefonefuncionario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonefuncionario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonefuncionario', array());

        return parent::getTelefonefuncionario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatanasc($datanasc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatanasc', array($datanasc));

        return parent::setDatanasc($datanasc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatanasc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatanasc', array());

        return parent::getDatanasc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAdmissao($dataAdmissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAdmissao', array($dataAdmissao));

        return parent::setDataAdmissao($dataAdmissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAdmissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAdmissao', array());

        return parent::getDataAdmissao();
    }

    /**
     * {@inheritDoc}
     */
    public function getProjetoprojeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjetoprojeto', array());

        return parent::getProjetoprojeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrauInstrucao($grauInstrucao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrauInstrucao', array($grauInstrucao));

        return parent::setGrauInstrucao($grauInstrucao);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrauInstrucao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrauInstrucao', array());

        return parent::getGrauInstrucao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacao($formacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacao', array($formacao));

        return parent::setFormacao($formacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacao', array());

        return parent::getFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuncao($funcao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuncao', array($funcao));

        return parent::setFuncao($funcao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuncao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuncao', array());

        return parent::getFuncao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioInicio($horarioInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioInicio', array($horarioInicio));

        return parent::setHorarioInicio($horarioInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioInicio', array());

        return parent::getHorarioInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioFim($horarioFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioFim', array($horarioFim));

        return parent::setHorarioFim($horarioFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioFim', array());

        return parent::getHorarioFim();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
