<?php

namespace DoctrineORMModule\Proxy\__CG__\Sala\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReservaSala extends \Sala\Entity\ReservaSala implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'idreservaSala', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'objetivo', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataInicio', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataFim', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'salaReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'professorReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'funcionarioReserva');
        }

        return array('__isInitialized__', 'inputFilter', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'idreservaSala', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'objetivo', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataInicio', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataFim', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'dataReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'salaReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'professorReserva', '' . "\0" . 'Sala\\Entity\\ReservaSala' . "\0" . 'funcionarioReserva');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReservaSala $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdReservaSala()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdReservaSala', array());

        return parent::getIdReservaSala();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivo($objetivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivo', array($objetivo));

        return parent::setObjetivo($objetivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivo', array());

        return parent::getObjetivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataReserva($dataReserva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataReserva', array($dataReserva));

        return parent::setDataReserva($dataReserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataReserva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataReserva', array());

        return parent::getDataReserva();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaReserva(\Sala\Entity\Sala $salaReserva = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaReserva', array($salaReserva));

        return parent::setSalaReserva($salaReserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaReserva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaReserva', array());

        return parent::getSalaReserva();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuncionarioReserva(\Funcionario\Entity\Funcionario $funcionarioReserva = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuncionarioReserva', array($funcionarioReserva));

        return parent::setFuncionarioReserva($funcionarioReserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuncionarioReserva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuncionarioReserva', array());

        return parent::getFuncionarioReserva();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessorReserva(\Professor\Entity\Professor $professorReserva = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessorReserva', array($professorReserva));

        return parent::setProfessorReserva($professorReserva);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessorReserva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessorReserva', array());

        return parent::getProfessorReserva();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
