<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Salas';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('sala', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar nova Sala</a>
            <a class="btn btn-default" href="<?php echo $this->url('sala', array('action'=>'print'));?>"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <tr>
            <th>Nome</th>
            <th>Local</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($salas as $sala) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($sala->getNome());?></td>
            <td><?php echo $this->escapeHtml($sala->getLocallocal()->getNomelocal());?></td>
            <td>
                 <a class="btn btn-info" href="<?php echo $this->url('sala',
                    array('action'=>'edit', 'id' => $sala->getIdsala()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('sala',
                    array('action'=>'delete', 'id' => $sala->getIdsala()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('sala',
                    array('action'=>'view', 'id' => $sala->getIdsala()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

