<div class="row">
<div class="col-md-12">
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Adicionar novo professor';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('professor', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('matriculaprofessor'))."\n"?>
	<?php echo $this->formText($form->get('matriculaprofessor')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('nomeprofessor'))."\n" ?>
	<?php echo $this->formText($form->get('nomeprofessor')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('emailprofessor'))."\n" ?>
	<?php echo $this->formText($form->get('emailprofessor')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('telefoneprofessor'))."\n" ?>
	<?php echo $this->formText($form->get('telefoneprofessor')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('areadeatuacao'))."\n" ?>
	<?php echo $this->formText($form->get('areadeatuacao')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('formacao'))."\n" ?>
	<?php echo $this->formText($form->get('formacao')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('titulacao'))."\n" ?>
	<?php echo $this->formText($form->get('titulacao')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('classe'))."\n" ?>
	<?php echo $this->formText($form->get('classe')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('regimedetrabalho'))."\n" ?>
	<?php echo $this->formText($form->get('regimedetrabalho')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('tipovinculo'))."\n" ?>
	<?php echo $this->formText($form->get('tipovinculo')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('datanasc'))."\n" ?>
	<?php echo $this->formText($form->get('datanasc')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('departamentodepartamento'))."\n" ?>
	<?php echo $this->formSelect($form->get('departamentodepartamento')) ?>
</div>
<?php echo $this->formSubmit($form->get('submit')) ?>



<?php echo $this->form()->closeTag(); ?>

</div>
</div>
</div>