<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('professor', array('action'=>'add'));?>">Add new professor</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($professores as $professor) : ?>
<tr>
    <td><?php echo $this->escapeHtml($professor->getNomeProfessor());?></td>
    <td><?php echo $this->escapeHtml($professor->getEmailProfessor());?></td>
    <td>
        <a href="<?php echo $this->url('professor',
            array('action'=>'edit', 'id' => $professor->getIdProfessor()));?>">Edit</a>
        <a href="<?php echo $this->url('professor',
            array('action'=>'delete', 'id' => $professor->getIdProfessor()));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
