<div class="panel panel-default">
	<?php
	// module/Album/view/album/album/index.phtml:

	$title = 'Professores';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
	    <h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<p>
		    <a class="btn btn-success" href="<?php echo $this->url('professor', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Professor</a>
		</p>

		<table class="table">
		<thead>
		    <th>Nome</th>
		    <th>Email</th>
		    <th>&nbsp;</th>
		</thead>
		<?php foreach ($professores as $professor) : ?>
		<tr>
		    <td><?php echo $this->escapeHtml($professor->getNomeProfessor());?></td>
		    <td><?php echo $this->escapeHtml($professor->getEmailProfessor());?></td>
		    <td>
		        <a class="btn btn-info" href="<?php echo $this->url('professor',
		            array('action'=>'edit', 'id' => $professor->getIdProfessor()));?>"><span class="glyphicon glyphicon-edit"></span> Edit</a>

		        <a class="btn btn-danger" href="<?php echo $this->url('professor',
		            array('action'=>'delete', 'id' => $professor->getIdProfessor()));?>"><span class="glyphicon glyphicon-remove"></span> Delete</a>
		        <a class="btn btn-primary" href="<?php echo $this->url('professor',
                    array('action'=>'view', 'id' => $professor->getIdprofessor()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
		    </td>
		</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div>
