<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Professor '. $professor->getNomeprofessor();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $professor->getNomeprofessor(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Matricula</strong></td>
			    		<td><?php echo $professor->getMatriculaprofessor(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Email</strong></td>
			    		<td><?php echo $professor->getEmailprofessor(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Telefone</strong></td>
			    		<td><?php echo $professor->getTelefoneprofessor(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Área de Atuação</strong></td>
			    		<td><?php echo $professor->getAreadeatuacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Formação</strong></td>
			    		<td><?php echo $professor->getFormacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Titulação</strong></td>
			    		<td><?php echo $professor->getTitulacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Classe</strong></td>
			    		<td><?php echo $professor->getClasse(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Regime de trabalho</strong></td>
			    		<td><?php echo $professor->getRegimedetrabalho(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Tipo de vinculo </strong></td>
			    		<td><?php echo $professor->getTipovinculo(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Nascimento</strong></td>
			    		<td><?php echo $professor->getDatanasc()->format('d/m/Y'); ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
	</div>

	<div class="col-md-5">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1>Projetos que Coordena</h1>
            </div>
            <ul class="list-group">
            	<?php
            	$projetos = $professor->getProfessorCoordProjeto()->toArray();    //deixei igual para rodar.        	
            	if(!$projetos)
            		echo "<li class=\"list-group-item\">Nenhum</li>";

            	foreach($projetos as $p) : ?>
					<li class="list-group-item">
						<span class="glyphicon glyphicon-briefcase"></span> 
						<?php echo $p->getTitulo() ?>
					</li>
				<?php endforeach ?>
            </ul>
            <!-- List group -->
        </div>
    </div>


	<div class="col-md-5">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1>Projetos que Participa</h1>
            </div>
            <ul class="list-group">
            	<?php
            	$projetos = $professor->getProjetoprojeto()->toArray();
            	
            	if(!$projetos)
            		echo "<li class=\"list-group-item\">Nenhum</li>";

            	foreach($projetos as $p) : ?>
					<li class="list-group-item">
						<span class="glyphicon glyphicon-briefcase"></span> 
						<?php echo $p->getTitulo() ?>
					</li>
				<?php endforeach ?>
            </ul>
            <!-- List group -->
        </div>
    </div>



</div>
