<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Grupo de Pesquisa';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('grupopesquisa', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idGrupoPesquisa')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('nomeGrupoPesquisa'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('nomeGrupoPesquisa')) ?>
				<?php echo $this->formElementErrors($form->get('nomeGrupoPesquisa')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('pesquisadorresponsavel'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('pesquisadorresponsavel')) ?>
				<?php echo $this->formElementErrors($form->get('pesquisadorresponsavel')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('objetivoGeral'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('objetivoGeral')) ?>
				<?php echo $this->formElementErrors($form->get('objetivoGeral')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('linhaPesquisa'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('linhaPesquisa')) ?>
				<?php echo $this->formElementErrors($form->get('linhaPesquisa')) ?>
			</div>
		</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('salasala'))."\n" ?>
		<div class="col-lg-10">
			<?php echo $this->formSelect($form->get('salasala')) ?>
			<?php echo $this->formElementErrors($form->get('salasala')) ?>
		</div>
	</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('areasGrupoPesquisa'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('areasGrupoPesquisa')) ?>
				<?php echo $this->formElementErrors($form->get('areasGrupoPesquisa')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>


