<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Grupos de Pesquisa';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('grupopesquisa', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar novo Grupo de Pesquisa</a>
            <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <tr>
            <th>Nome</th>
            <th>Pesquisador Responsavel</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($grupoPesquisas as $grupoPesquisa) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($grupoPesquisa->getNomeGrupoPesquisa());?></td>
            <td><?php echo $this->escapeHtml($grupoPesquisa->getPesquisadorresponsavel()->getNomeprofessor());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('grupopesquisa',
                    array('action'=>'edit', 'id' => $grupoPesquisa->getIdGrupoPesquisa()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('grupopesquisa',
                    array('action'=>'delete', 'id' => $grupoPesquisa->getIdGrupoPesquisa()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('grupopesquisa',
                    array('action'=>'view', 'id' => $grupoPesquisa->getIdGrupoPesquisa()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
