<link href="/css/bootstrap.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-theme.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/style.css" print="screen" rel="stylesheet" type="text/css">
<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Individual do Grupo de Pesquisa: ' . $gruposPesquisa->getNomeGrupoPesquisa();
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <center><strong>Dados</strong></center>
                </div>
                <div class="panel-body">
                    <table class="table">
                    <tr>
                        <td><strong>Grupo</strong></td>
                        <td><?php echo $gruposPesquisa->getNomeGrupoPesquisa(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Pesquisador Responsável</strong></td>
                        <td><?php echo $gruposPesquisa->getPesquisadorresponsavel()->getNomeprofessor(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Coordenador da Pesquisa</strong></td>
                        <td><?php echo $gruposPesquisa->getCoordPesquisa()->getNomeprofessor(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Linha de Pesquisa</strong></td>
                        <td><?php echo $gruposPesquisa->getlinhaPesquisa(); ?></td>
                    </tr>

                    <tr>
                        <td><strong>Objetivo Geral</strong></td>
                       <td><?php echo $gruposPesquisa->getObjetivoGeral(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Sala</strong></td>
                        <td><?php echo $gruposPesquisa->getSalasala()->getNome(); ?></td>
                    </tr>
                </table>
                </div>
                <div class="panel-footer">
                </div>
                <!-- List group -->
            </div>
        </div>




<style media="print">
    .btn-default {
        display: none;    
    }
    .btn {
        display: none;
    }
</style>
<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
<center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
<div class="row">
    


    

    
</div>