<link href="/css/bootstrap.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-theme.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/style.css" print="screen" rel="stylesheet" type="text/css">

<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Geral de Grupo de Pesquisa';
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <table class="table">
        <thead>
            <th>Nome</th>
            <th>Objetivo Geral</th>
            <th>Linha de Pesquisa</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($grupos as $grupo) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($grupo->getNomeGrupoPesquisa());?></td>
            <td><?php echo $this->escapeHtml($grupo->getObjetivoGeral());?></td>
            <td><?php echo $this->escapeHtml($grupo->getlinhaPesquisa());?></td>
        </tr>
        <?php endforeach; ?>
        </table>
        <a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
        <center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
    </div>

</div>


</div>


