<div class="row">
    
    <div class="col-md-6">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Grupo de Pesquisa '. $grupoPesquisa->getNomeGrupoPesquisa();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Id</strong></td>
			    		<td><?php echo $grupoPesquisa->getIdGrupoPesquisa(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Grupo</strong></td>
			    		<td><?php echo $grupoPesquisa->getNomeGrupoPesquisa(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Pesquisador Responsavel</strong></td>
			    		<td><?php echo $grupoPesquisa->getPesquisadorresponsavel()->getNomeprofessor(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Áreas</strong></td>
			    		<td><?php echo $grupoPesquisa->getAreasGrupoPesquisa(); ?></td>
			    	</tr>
			    </table>
			</div>
		</div>
		<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
		<a class="btn btn-default" href="<?php echo $this->url('grupoPesquisa', array('action'=>'print'));?>"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
	</div>

</div>
