<div class="panel panel-info">
	<?php
	// module/Album/view/album/album/edit.phtml:
	$title = 'Editar Projeto';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url(
		    'projeto',
		    array(
		        'action' => 'edit',
		        'id'     => $this->id,
		    )
		));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
			<?php echo $this->formHidden($form->get('id')) ?>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('titulo'))."\n"?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('titulo')) ?>
					<?php echo $this->formElementErrors($form->get('titulo')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('grupoPesquisaProjeto'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formSelect($form->get('grupoPesquisaProjeto')) ?>
					<?php echo $this->formElementErrors($form->get('grupoPesquisaProjeto')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('objetivogeral'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('objetivogeral')) ?>
					<?php echo $this->formElementErrors($form->get('objetivogeral')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('professorcoordenador'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formSelect($form->get('professorcoordenador')) ?>
					<?php echo $this->formElementErrors($form->get('professorcoordenador')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('objetivoespec'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('objetivoespec')) ?>
					<?php echo $this->formElementErrors($form->get('objetivoespec')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('resultadosesperados'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('resultadosesperados')) ?>
					<?php echo $this->formElementErrors($form->get('resultadosesperados')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('finaciamento'))."\n" ?>
				<div class="col-lg-4">
					<?php echo $this->formRadio($form->get('finaciamento')) ?>
					<?php echo $this->formElementErrors($form->get('finaciamento')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('tipoPesquisa'))."\n" ?>
				<div class="col-lg-4">
					<?php echo $this->formRadio($form->get('tipoPesquisa')) ?>
					<?php echo $this->formElementErrors($form->get('tipoPesquisa')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('fontefinaciamento'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('fontefinaciamento')) ?>
					<?php echo $this->formElementErrors($form->get('fontefinaciamento')) ?>
				</div>
			</div>
			<div class="form-group">
		    	<div class="col-lg-offset-2 col-lg-10">
					<?php echo $this->formSubmit($form->get('submit')) ?>
				</div>
			</div>

		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
