<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Projetos';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('projeto', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar novo Projeto</a>
        <a class="btn btn-default" href="<?php echo $this->url('projeto', array('action'=>'relatorio'));?>"><span class="glyphicon glyphicon-list-alt"></span> Relatório</a>
        </p>

        <table class="table">
        <tr>
            <th>Título</th>
            <th>Grupo de Pesquisa</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($projetos as $projeto) : ?>
        <tr>
            <td><?php echo substr($this->escapeHtml($projeto->getTitulo()), 0, 20);?></td>
            <td><?php echo substr($this->escapeHtml($projeto->getGrupoPesquisaProjeto()->getNomeGrupoPesquisa()), 0, 75);?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('projeto',
                    array('action'=>'edit', 'id' => $projeto->getIdprojeto()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('projeto',
                    array('action'=>'delete', 'id' => $projeto->getIdprojeto()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('projeto',
                    array('action'=>'view', 'id' => $projeto->getIdprojeto()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
