<link href="/css/bootstrap.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-theme.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/style.css" print="screen" rel="stylesheet" type="text/css">
<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Individual do Projeto: ' . $projeto->getTitulo();
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <center><strong>Dados</strong></center>
                </div>
                <div class="panel-body">
                    <table class="table">
                    <tr>
                        <td><strong>Título</strong></td>
                        <td><?php echo $projeto->getTitulo(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Objetivo Geral</strong></td>
                        <td><?php echo $projeto->getObjetivogeral(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Objetivo Específico</strong></td>
                        <td><?php echo $projeto->getObjetivoespec(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Resultados Esperados</strong></td>
                        <td><?php echo $projeto->getResultadosesperados(); ?></td>
                    </tr>

                    <tr>
                        <td><strong>Financiamento</strong></td>
                       <td><?php echo $projeto->getFinaciamento() ? 'Sim' : 'Não'; ?></td>
                    </tr>
                    <tr>
                        <td><strong>Tipo</strong></td>
                        <td><?php echo $projeto->getTipoPesquisa() ? 'Pesquisa' : 'Extensão'; ?></td>
                    </tr>
                    <tr>
                        <td><strong>Fonte de Financiamento</strong></td>
                       <td><?php echo $projeto->getFontefinaciamento(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Coordenador</strong></td>
                        <td><?php echo $projeto->getProfessorcoordenador()->getNomeprofessor(); ?></td>
                    </tr>
                    <tr>
                        <td><strong>Grupo de Pesquisa</strong></td>
                       <td><?php echo $projeto->getGrupoPesquisaProjeto()->getNomeGrupoPesquisa(); ?><td>
                    </tr>
                </table>
                </div>
                <div class="panel-footer">
                </div>
                <!-- List group -->
            </div>
        </div>


   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <center><strong>Professores</strong></center>
            </div>

            <div class="panel-body">
                <?php 
                //var_dump(projetos); exit;
               $proj =  $projeto->getProfessorprofessor()->toArray();
                foreach($proj as $p): ?>
                    <ul class="list-group">
                        <li class="list-group-item"><?php echo  $p->getNomeprofessor(); ?></li>
                    </ul>
                <?php endforeach; ?>
            </div>
            <div class="panel-footer">
            </div>
        </div>
</div>



   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <center><strong>Alunos</strong></center>
            </div>

            <div class="panel-body">
                <?php 
                //var_dump(projetos); exit;
               $proj =  $projeto->getAlunoaluno()->toArray();
                foreach($proj as $p): ?>
                    <ul class="list-group">
                        <li class="list-group-item"><?php echo  $p->getNomealuno(); ?></li>
                    </ul>
                <?php endforeach; ?>
            </div>
            <div class="panel-footer">
            </div>
        </div>
</div>


<style media="print">
    .btn-default {
        display: none;    
    }
    .btn {
        display: none;
    }
</style>
<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
<center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
<div class="row">
    


    

    
</div>