<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Reserva de Sala';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('reservasala/default', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		
		<div class="form-group">
			<?php echo $this->formLabel($form->get('objetivo'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('objetivo')) ?>
				<?php echo $this->formElementErrors($form->get('objetivo')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('dataInicio'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('dataInicio')) ?>
				<?php echo $this->formElementErrors($form->get('dataInicio')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('dataFim'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('dataFim')) ?>
				<?php echo $this->formElementErrors($form->get('dataFim')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('dataReserva'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('dataReserva')) ?>
				<?php echo $this->formElementErrors($form->get('dataReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('salaReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('salaReserva')) ?>
				<?php echo $this->formElementErrors($form->get('salaReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('funcionarioReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('funcionarioReserva')) ?>
				<?php echo $this->formElementErrors($form->get('funcionarioReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('professorReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('professorReserva')) ?>
				<?php echo $this->formElementErrors($form->get('professorReserva')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script>
jQuery(function($){
   $("#dataInicio").mask("99:99");
   $("#dataFim").mask("99:99");
});
</script>
<script>
$(function() {
    $( "#dataFrequencia" ).datepicker({dateFormat: 'dd/mm/yy'});
});
</script>


