<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Reserva de Sala';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php if (isset($mensagem)) : ?>
    		<div class="alert alert-warning">
    			<?php echo $mensagem ?>
    			<button type="button" class="close" data-dismiss="alert">×</button>
    		</div>
    	<?php endif;
		$form = $this->form;
		$form->setAttribute('action', $this->url('reservasala/default', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		
		<div class="form-group">
			<?php echo $this->formLabel($form->get('objetivo'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('objetivo')) ?>
				<?php echo $this->formElementErrors($form->get('objetivo')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('dataInicio'))."\n"?>
			<div class="col-lg-2">
				<?php echo $this->formText($form->get('dataInicio')) ?>
				<?php echo $this->formElementErrors($form->get('dataInicio')) ?>
			</div>
			<?php echo $this->formLabel($form->get('dataFim'))."\n"?>
			<div class="col-lg-2">
				<?php echo $this->formText($form->get('dataFim')) ?>
				<?php echo $this->formElementErrors($form->get('dataFim')) ?>
			</div>
			<?php echo $this->formLabel($form->get('dataReserva'))."\n"?>
			<div class="col-lg-2">
				<?php echo $this->formText($form->get('dataReserva')) ?>
				<?php echo $this->formElementErrors($form->get('dataReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('salaReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('salaReserva')) ?>
				<?php echo $this->formElementErrors($form->get('salaReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('funcionarioReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('funcionarioReserva')) ?>
				<?php echo $this->formElementErrors($form->get('funcionarioReserva')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('professorReserva'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('professorReserva')) ?>
				<?php echo $this->formElementErrors($form->get('professorReserva')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jquery.timepicker.js' ?>"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() . '/css/jquery.timepicker.css' ?>" />
<script>
$(function() {
    $( "#dataReserva" ).datepicker({dateFormat: 'dd/mm/yy'});
    $('#dataInicio').timepicker({ 'timeFormat': 'H:i:s', 'step': 15 });
    $('#dataFim').timepicker({ 'timeFormat': 'H:i:s', 'step': 15 });
});
</script>



