<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:

    $title = 'Reserva de Sala';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('reservasala', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Reservar de Sala</a>
        </p>

        <table class="table">
        <thead>
            <th>Sala</th>
            <th>Professor</th>
            <th>Objetivo</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($reservasalas as $reservasala) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($reservasala->getSalasala()->getNome());?></td>
            <td><?php echo $this->escapeHtml($reservasala->getProfessorprofessor()->getNomeprofessor());?></td>
            <td><?php echo $this->escapeHtml($reservasala->getObjetivo());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('reservasala',
                    array('action'=>'edit', 'id' => $reservasala->getIdreservasala()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                <a class="btn btn-danger" href="<?php echo $this->url('reservasala',
                    array('action'=>'delete', 'id' => $reservasala->getIdreservasala()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

