<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Geral de Reservas de Sala';
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="/reserva-sala/relatorio" method="post" name="filtro" class="form-horizontal">
                        <fieldset>
                            <legend>Filtro</legend>
                            <div class="form-group">
                                <label class="col-md-1 control-label" for="selectbasic">Funcionário</label>
                                <div class="col-md-4">
                                    <select id="selectbasic" name="selectfuncionario" class="form-control">
                                        <option value="-1">Todos os Funcionários</option>
                                        <?php foreach($funcionarios as $f) : ?>
                                            <?php if ($_POST['selectfuncionario'] == $f->getIdfuncionario()) : ?>
                                                <option value="<?php echo $f->getIdfuncionario()?>" selected="selected"><?php echo $f->getNomefuncionario()?></option>
                                            <?php else: ?>
                                                <option value="<?php echo $f->getIdfuncionario()?>"><?php echo $f->getNomefuncionario()?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <label class="col-md-2 control-label" for="selectbasic">Sala</label>
                                <div class="col-md-4">
                                    <select id="selectbasic" name="selectsala" class="form-control">
                                        <option value="-1">Todas as Salas</option>
                                        <?php foreach($salas as $s) : ?>
                                            <?php if ($_POST['selectsala'] == $s->getIdsala()) : ?>
                                                <option value="<?php echo $s->getIdsala()?>" selected="selected"><?php echo $s->getNome()?></option>
                                            <?php else: ?>
                                                <option value="<?php echo $s->getIdsala()?>"><?php echo $s->getNome()?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-1 control-label" for="selectbasic">Professor</label>
                                <div class="col-md-4">
                                    <select id="selectbasic" name="selectprofessor" class="form-control">
                                        <option value="-1">Todos os Professores</option>
                                        
                                        <?php foreach($professores as $p) : ?>
                                            <?php if ($_POST['selectprofessor'] == $p->getIdprofessor()) : ?>
                                                <option value="<?php echo $p->getIdprofessor()?>" selected="selected"><?php echo $p->getNomeprofessor()?></option>
                                            <?php else: ?>
                                                <option value="<?php echo $p->getIdprofessor()?>"><?php echo $p->getNomeprofessor()?></option>
                                            <?php endif; ?>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                                <label class="col-md-2 control-label" for="textinput">Objetivo</label>  
                                <div class="col-md-4">
                                    <?php if (isset($_POST['objetivo'])): ?>
                                        <input id="objetivo" name="objetivo" placeholder="Todos os objetivos" value="<?php echo $_POST['objetivo'] ?>" class="form-control input-md" type="text">
                                    <?php else: ?>
                                        <input id="objetivo" name="objetivo" placeholder="Todos os objetivos" class="form-control input-md" type="text">
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-1 control-label" for="textinput">Data</label>
                                <div class="col-md-4">
                                    <?php if (isset($_POST['data'])): ?>
                                        <input id="data" name="data" placeholder="Todas as datas" value="<?php echo $_POST['data'] ?>" class="form-control input-md" type="text">
                                    <?php else: ?>
                                        <input id="data" name="data" placeholder="Todas as datas" class="form-control input-md" type="text">
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-10 control-label" for="singlebutton"></label>
                                <div class="col-md-1">
                                    <button id="singlebutton" name="singlebutton" class="btn btn-primary">Filtrar</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <table class="table">
                    <thead>
                        <th>Objetivo</th>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Dia</th>
                        <th>Sala</th>
                        <th>Funcionário</th>
                        <th>Professor</th>
                        <th>&nbsp;</th>
                    </thead>
                    <?php foreach ($reservasSala as $reservas) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($reservas->getObjetivo());?></td>
                            <td><?php echo $this->escapeHtml($reservas->getDataInicio()->format('H:i:s'));?></td>
                            <td><?php echo $this->escapeHtml($reservas->getDataFim()->format('H:i:s'));?></td>
                            <td><?php echo $this->escapeHtml($reservas->getDataReserva()->format('d/m/Y'));?></td>
                            <td><?php echo $this->escapeHtml($reservas->getSalaReserva()->getNome());?></td>
                            <td><?php echo $this->escapeHtml($reservas->getFuncionarioReserva()->getNomefuncionario());?></td>
                            <td><?php echo $this->escapeHtml($reservas->getProfessorReserva()->getNomeprofessor());?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<script>
$(function() {
    $( "#data" ).datepicker({dateFormat: 'dd/mm/yy'});
});
</script>
<style media="print">
    .btn-default {
        display: none;    
    }
    .btn {
        display: none;
    }
</style>
<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
<center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
