<div class="row">
<div class="col-md-12">
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Adicionar novo departamento';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('departamento', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('nomedepartamento'))."\n"?>
	<?php echo $this->formText($form->get('nomedepartamento')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('descricaodepartamento'))."\n" ?>
	<?php echo $this->formText($form->get('descricaodepartamento')) ?>
</div>

<?php echo $this->formSubmit($form->get('submit')) ?>



<?php echo $this->form()->closeTag(); ?>

</div>
</div>