<div class="panel panel-default">
	<?php
	// module/Album/view/album/album/index.phtml:

	$title = 'Departamentos';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
	    <h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<p>
		    <a class="btn btn-success" href="<?php echo $this->url('departamento/default', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Departamento</a>
		    <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
		</p>

		<table class="table">
		<thead>
		    <th>Nome</th>
		    <th>Descrição</th>
		    <th>&nbsp;</th>
		</thead>
		<?php foreach ($this->data as $departamento) : ?>
		<tr>
		    <td><?php echo $this->escapeHtml($departamento->getNomeDepartamento());?></td>
		    <td><?php echo $this->escapeHtml($departamento->getDescricaoDepartamento());?></td>
		    <td>
		        <a class="btn btn-info" href="<?php echo $this->url('departamento/default',
		            array('action'=>'edit', 'id' => $departamento->getIdDepartamento()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

		        <a class="btn btn-danger" href="<?php echo $this->url('departamento/default',
		            array('action'=>'delete', 'id' => $departamento->getIdDepartamento()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>

		        <a class="btn btn-primary" href="<?php echo $this->url('departamento/default',
                    array('action'=>'view', 'id' => $departamento->getIdDepartamento()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
		    </td>
		</tr>
		<?php endforeach; ?>
		</table>
		<center>
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'professor/paginator')); ?>
        </center>
	</div>
</div>