<div class="row">
<div class="col-md-12">
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Adicionar novo aluno';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('aluno', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('nomealuno'))."\n"?>
	<?php echo $this->formText($form->get('nomealuno')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('emailaluno'))."\n" ?>
	<?php echo $this->formText($form->get('emailaluno')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('telefonealuno'))."\n" ?>
	<?php echo $this->formText($form->get('telefonealuno')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('matriculaaluno'))."\n" ?>
	<?php echo $this->formText($form->get('matriculaaluno')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('bolsista'))."\n" ?>
	<?php echo $this->formText($form->get('bolsista')) ?>
</div>
<div class="form-group">
	<?php echo $this->formLabel($form->get('datanasc'))."\n" ?>
	<?php echo $this->formText($form->get('datanasc')) ?>
</div>

<?php echo $this->formSubmit($form->get('submit')) ?>



<?php echo $this->form()->closeTag(); ?>

</div>
</div>