<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Alunos';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <a class="btn btn-success" href="<?php echo $this->url('aluno', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar aluno</a>
        

        <table class="table">
        <thead>
            <th>Nome</th>
            <th>Email</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($alunos as $aluno) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($aluno->getNomealuno());?></td>
            <td><?php echo $this->escapeHtml($aluno->getEmailaluno());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('aluno',
                    array('action'=>'edit', 'id' => $aluno->getIdaluno()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('aluno',
                    array('action'=>'delete', 'id' => $aluno->getIdaluno()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('aluno',
                    array('action'=>'view', 'id' => $aluno->getIdaluno()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>