<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Geral de Alunos';
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <table class="table">
        <thead>
            <th>Nome</th>
            <th>Email</th>
            <th>Curso</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($alunos as $aluno) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($aluno->getNomealuno());?></td>
            <td><?php echo $this->escapeHtml($aluno->getEmailaluno());?></td>
            <td><?php echo $this->escapeHtml($aluno->getCursoAluno()->getNomeCurso());?></td>
        </tr>
        <?php endforeach; ?>
        </table>
        <a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
        <center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
    </div>

</div>