<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Aluno '. $aluno->getNomealuno();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $aluno->getNomealuno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>E-mail</strong></td>
			    		<td><?php echo $aluno->getEmailaluno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Telefone</strong></td>
			    		<td><?php echo $aluno->getTelefonealuno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Matrícula</strong></td>
			    		<td><?php echo $aluno->getMatriculaaluno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Bolsista</strong></td>
			    		<td><?php echo $aluno->getBolsista() ? 'Sim' : 'Não'; ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Nascimento</strong></td>
			    		<td><?php echo $aluno->getDatanasc()->format('d/m/Y'); ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
	</div>

	<div class="col-md-5">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1>Projetos</h1>
            </div>
            <ul class="list-group">
            	<?php
            	$projetos = $aluno->getProjetoprojeto()->toArray();
            	
            	if(!$projetos)
            		echo "<li class=\"list-group-item\">Nenhum</li>";

            	foreach($projetos as $p) : ?>
					<li class="list-group-item">
						<span class="glyphicon glyphicon-briefcase"></span> 
						<?php echo $p->getTitulo() ?>
					</li>
				<?php endforeach ?>
            </ul>
            <!-- List group -->
        </div>
    </div>
</div>
