<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			
			$title = 'Aluno '. $aluno->getNomealuno();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $aluno->getNomealuno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>E-mail</strong></td>
			    		<td><?php echo $aluno->getEmailaluno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Telefone</strong></td>
			    		<td><?php echo $aluno->getTelefonealuno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Matrícula</strong></td>
			    		<td><?php echo $aluno->getMatriculaaluno(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Curso</strong></td>
			    		<td><?php echo $aluno->getCursoAluno()->getNomeCurso(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Bolsista</strong></td>
			    		<td><?php echo $aluno->getBolsista() ? 'Sim' : 'Não'; ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Nascimento</strong></td>
			    		<td><?php echo $aluno->getDatanasc()->format('d/m/Y'); ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
		<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
		<a class="btn btn-default" href="<?php echo $this->url('aluno/default', array('action'=>'relatorioindividual', 'id' => $aluno->getIdaluno()));?>"><span class="glyphicon glyphicon-list-alt"></span> Relatório</a>
	</div>
</div>
