<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Cursos';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('curso', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar novo Curso</a>
            <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <tr>
            <th>Curso</th>
            <th>Departamento</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($cursos as $curso) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($curso->getNomeCurso());?></td>
            <td><?php echo $this->escapeHtml($curso->getDepartamentoCurso()->getNomeDepartamento());?></td>
            <td>
                 <a class="btn btn-info" href="<?php echo $this->url('curso',
                    array('action'=>'edit', 'id' => $curso->getIdcurso()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('curso',
                    array('action'=>'delete', 'id' => $curso->getIdcurso()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('curso',
                    array('action'=>'view', 'id' => $curso->getIdcurso()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

