<link href="/css/bootstrap.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-theme.min.css" print="screen" rel="stylesheet" type="text/css">
<link href="/css/style.css" print="screen" rel="stylesheet" type="text/css">
<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Relatório Geral de Cursos';
    
    $this->headTitle($title);

    ?>

    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <table class="table">
        <thead>
            <th>Curso</th>
            <th>Departamento</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($cursos as $curso) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($curso->getNomeCurso());?></td>
            <td><?php echo $this->escapeHtml($curso->getDepartamentoCurso()->getNomedepartamento());?></td>
        </tr>
        <?php endforeach; ?>
        </table>
        
    </div>

</div>
<style media="print">
    .btn-default {
        display: none;    
    }
    .btn {
        display: none;
    }
</style>
<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
<center><a class="btn btn-default" href="javascript:self.print()" ><span class="glyphicon glyphicon-print"></span> Imprimir</a></center>
