<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Controle';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php if (isset($mensagem)) : ?>
    		<div class="alert alert-warning">
    			<?php echo $mensagem ?>
    			<button type="button" class="close" data-dismiss="alert">×</button>
    		</div>
    	<?php endif;
		$form = $this->form;
		$form->setAttribute('action', $this->url('controle/default', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idControle')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('alunoControle'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('alunoControle')) ?>
				<?php echo $this->formElementErrors($form->get('alunoControle')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('cursoControle'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('cursoControle')) ?>
				<?php echo $this->formElementErrors($form->get('cursoControle')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('salaControle'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('salaControle')) ?>
				<?php echo $this->formElementErrors($form->get('salaControle')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('responsavelControle'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('responsavelControle')) ?>
				<?php echo $this->formElementErrors($form->get('responsavelControle')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('objetivoControle'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('objetivoControle')) ?>
				<?php echo $this->formElementErrors($form->get('objetivoControle')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
