<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Tombo '. $tombo->getNumeroTombo();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Id</strong></td>
			    		<td><?php echo $tombo->getIdTombo(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Número</strong></td>
			    		<td><?php echo $tombo->getNumeroTombo(); ?></td>
			    	</tr>
			    </table>
			</div>
		</div>
	</div>
</div>


