<div class="panel panel-success">
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Adicionar novo Tipo De Equipamento';
$this->headTitle($title);
?>
<div class="panel-heading">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
<div class="panel-body">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('tipoequipamento', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('nometipoequipamento'))."\n"?>
	<div class="col-lg-10">
		<?php echo $this->formText($form->get('nometipoequipamento')) ?>
		<?php echo $this->formElementErrors($form->get('nometipoequipamento')) ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('descricaotipoequipamento'))."\n" ?>
	<div class="col-lg-10">
		<?php echo $this->formText($form->get('descricaotipoequipamento')) ?>
		<?php echo $this->formElementErrors($form->get('descricaotipoequipamento')) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-lg-offset-2 col-lg-10">
		<?php echo $this->formSubmit($form->get('submit')) ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>

</div>
</div>
<script>
jQuery(function($){
   //$("#datanasc").mask("99/99/9999");
  // $("#telefoneprofessor").mask("(99) 9999-9999");
});
</script>