<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:

    $title = 'Tipo Equipamento';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('tipoequipamento', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Tipo de Equipamento</a>
        </p>

        <table class="table">
        <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($tipoequipamentos as $tipoequipamento) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($tipoequipamento->getNometipoequipamento());?></td>
            <td><?php echo $this->escapeHtml($tipoequipamento->getDescricaotipoequipamento());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('tipoequipamento',
                    array('action'=>'edit', 'id' => $tipoequipamento->getIdtipoequipamento()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                <a class="btn btn-danger" href="<?php echo $this->url('tipoequipamento',
                    array('action'=>'delete', 'id' => $tipoequipamento->getIdtipoequipamento()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

