<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SG '. $this->translate('Avatar'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('SGCPDS') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>">Inicio</a></li>
                        <li><a href="<?php echo $this->url('aluno') ?>">Aluno</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projeto<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/projeto">Projeto</a></li>
                                <li><a href="/grupo-pesquisa">Grupo de Pesquisa</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('curso') ?>">Curso</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Professor<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/professor">Professor</a></li>
                                <li><a href="/departamento">Departamento</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Funcionario<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/funcionario">Funcionario</a></li>
                                <li><a href="/frequencia">Frequencia</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Equipamento<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/equipamento">Equipamento</a></li>
                                <li><a href="/tipo-equipamento">Tipo de Equipamento</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sala<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/local">Local</a></li>
                                <li><a href="/sala">Sala</a></li>
                                <li><a href="/reserva-sala">Reserva</a></li>
                                <li><a href="/ocorrencia">Ocorrencia</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        
                        
                        <?php if($user = $this->identity()) : ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-home"></span>  <?php echo $user->getUsername() ?> <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/user"><span class="glyphicon glyphicon-user"></span>  Principal</a></li>
                                    <li><a href="/edit-profile"><span class="glyphicon glyphicon-wrench"></span>   Perfil</a></li>
                                    <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>  Logout</a></li>
                                </ul>
                            </li>
                        <?php else : ?>
                            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> </i> Login</a></li>
                        <?php endif ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> Avatar. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
