<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:

    $title = 'Local';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('local', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Local</a>
        </p>

        <table class="table">
        <thead>
            <th>Nome</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($locais as $local) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($local->getNomelocal());?></td>
            
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('local',
                    array('action'=>'edit', 'id' => $local->getIdlocal()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                <a class="btn btn-danger" href="<?php echo $this->url('local',
                    array('action'=>'delete', 'id' => $local->getIdlocal()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                <a class="btn btn-primary" href="<?php echo $this->url('local',
                    array('action'=>'view', 'id' => $local->getIdlocal()));?>"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

