<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:
    $title = 'Áreas de Atuação';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('atuacao', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar nova Área de Atuação</a>
            <a class="btn btn-default" href="#"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
        </p>

        <table class="table">
        <tr>
            <th>Nome</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($atuacoes as $atuacao) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($atuacao->getNomeAreaAtuacao());?></td>
            <td>
                 <a class="btn btn-info" href="<?php echo $this->url('atuacao',
                    array('action'=>'edit', 'id' => $atuacao->getIdAreaAtuacao()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a class="btn btn-danger" href="<?php echo $this->url('atuacao',
                    array('action'=>'delete', 'id' => $atuacao->getIdAreaAtuacao()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

