<div class="panel panel-default">
	<div class="row">
		<form action="/busca/busca" method="post" name="busca" class="form-horizontal">
		  	<div class="col-lg-6">
		    	<div class="input-group">
		      		<input type="text" class="form-control" name="busca">
		      		<span class="input-group-btn">
		        		<button class="btn btn-default" type="submit">Go!</button>
		      		</span>
		    	</div><!-- /input-group -->
		  	</div><!-- /.col-lg-6 -->
		</form>
	</div><!-- /.row -->
</div>