<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar Ocorrência';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('ocorrencia', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		
		<div class="form-group">
			<?php echo $this->formLabel($form->get('observacao'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('observacao')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('reservaSalareservasala'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('reservaSalareservasala')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('funcionariofuncionario'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formSelect($form->get('funcionariofuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>


