<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Ocorrência '. $ocorrencia->getIdOcorrencia();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>Id</strong></td>
			    		<td><?php echo $ocorrencia->getIdOcorrencia(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Observação</strong></td>
			    		<td><?php echo $ocorrencia->getObservacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Sala</strong></td>
			    		<td><?php echo $ocorrencia->getReservaSalaOcorrencia()->getSalaReserva()->getNome(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Funcionário</strong></td>
			    		<td><?php echo $ocorrencia->getFuncionarioOcorrencia()->getNomefuncionario(); ?></td>
			    	</tr>
			    </table>
			</div>
		</div>
		<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
		<a class="btn btn-default" href="<?php echo $this->url('sala', array('action'=>'print'));?>"><span class="glyphicon glyphicon-list-alt"></span> Gerar Relatório</a>
	</div>

</div>
