<div class="panel panel-success">
<?php
// module/Album/view/album/album/add.phtml:

$title = 'Adicionar Equipamento';
$this->headTitle($title);
?>
<div class="panel-heading">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
<div class="panel-body">
<?php if (isset($mensagem)) : ?>
    		<div class="alert alert-warning">
    			<?php echo $mensagem ?>
    			<button type="button" class="close" data-dismiss="alert">×</button>
    		</div>
    	<?php endif;
$form = $this->form;
$form->setAttribute('action', $this->url('equipamento/default', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('ntombo'))."\n"?>
	<div class="col-lg-10">
		<?php echo $this->formText($form->get('ntombo')) ?>
		<?php echo $this->formElementErrors($form->get('ntombo')) ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('observacao'))."\n" ?>
	<div class="col-lg-10">
		<?php echo $this->formText($form->get('observacao')) ?>
		<?php echo $this->formElementErrors($form->get('observacao')) ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('tipoequipamentotipoequipamento'))."\n" ?>
	<div class="col-lg-10">
		<?php echo $this->formSelect($form->get('tipoequipamentotipoequipamento')) ?>
		<?php echo $this->formElementErrors($form->get('tipoequipamentotipoequipamento')) ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('salasala'))."\n" ?>
	<div class="col-lg-10">
		<?php echo $this->formSelect($form->get('salasala')) ?>
		<?php echo $this->formElementErrors($form->get('salasala')) ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('projetoprojeto'))."\n" ?>
	<div class="col-lg-10">
		<?php echo $this->formSelect($form->get('projetoprojeto')) ?>
		<?php echo $this->formElementErrors($form->get('projetoprojeto')) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-lg-offset-2 col-lg-10">
		<?php echo $this->formSubmit($form->get('submit')) ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>

</div>
</div>
