<div class="panel panel-default">
    <?php
    // module/Album/view/album/album/index.phtml:

    $title = 'Equipamento';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <a class="btn btn-success" href="<?php echo $this->url('equipamento', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Equipamento</a>
        </p>

        <table class="table">
        <thead>
            <th>N° Tombo</th>
            <th>Observação</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($equipamentos as $equipamento) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($equipamento->getNtombo());?></td>
            <td><?php echo $this->escapeHtml($equipamento->getObservacao());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('equipamento',
                    array('action'=>'edit', 'id' => $equipamento->getIdequipamento()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                <a class="btn btn-danger" href="<?php echo $this->url('equipamento',
                    array('action'=>'delete', 'id' => $equipamento->getIdequipamento()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>