<div class="panel panel-default">

    <?php
    // module/Album/view/album/album/index.phtml:

    $title = 'Equipamento';
    $this->headTitle($title);
    ?>
    <div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

    </div>
    <div class="panel-body">
            <form method="get">
            <div class="input-group pull-right col-lg-4">
                <input type="text" class="form-control" id="input-buscar" placeholder="Numero do tombo">
                <span class="input-group-btn">
                    <button class="btn btn-default" id="btn-buscar" type="button"><span class="glyphicon glyphicon-search"></span></button>
                </span>
            </div><!-- /input-group -->
            </form>
            <a class="btn btn-success" href="<?php echo $this->url('equipamento', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus"></span> Adicionar Equipamento</a>


        
                

        <table class="table">
        <thead>
            <th>N° Tombo</th>
            <th>Observação</th>
            <th>&nbsp;</th>
        </thead>
        <?php foreach ($equipamentos as $equipamento) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($equipamento->getNtombo());?></td>
            <td><?php echo $this->escapeHtml($equipamento->getObservacao());?></td>
            <td>
                <a class="btn btn-info" href="<?php echo $this->url('equipamento',
                    array('action'=>'edit', 'id' => $equipamento->getIdequipamento()));?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                <a class="btn btn-danger" href="<?php echo $this->url('equipamento',
                    array('action'=>'delete', 'id' => $equipamento->getIdequipamento()));?>"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

<script>
jQuery(function($){
    $('#btn-buscar').click(function(){
        id = $('#input-buscar').val();
        url = '/equipamento';
        if(id != '' && !isNaN(id) ){
            url += '/' + id;
        }
        $(window.location).attr('href', url);
    });
});
</script>
