<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Equipamento '. $equipamento->getNtombo();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
			    	<tr>
			    		<td><strong>N° Tombo</strong></td>
			    		<td><?php echo $equipamento->getNtombo(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Observação</strong></td>
			    		<td><?php echo $equipamento->getObservacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Tipo De Equipamento</strong></td>
			    		<td><?php echo $equipamento->getTipoequipamentotipoequipamento()->getNometipoequipamento; ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
	</div>

</div>