<?php
foreach($message as $k=>$m):
    $key = key($m);
    $message = current($m);
?>
    <div class="alert alert-<?php echo $key ?>">
        <button type="button" class="close" data-dimiss="alert">&times;</button>
        <strong><?php echo $key == success ? 'Sucesso!' : 'Erro!'?> </strong><?php echo $message?>
    </div>
<?php endforeach; ?>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="jumbotron">
                <h1>
                    Olá, Rose ou Jaque!
                </h1>
                <p>
                    Este é o Sistema de Gerenciamento de Informações do CPDS, chamado Avatar. Com ele vocês podem cadastrar alunos, projetos, professores, departamentos, cursos, funcionários e suas frequências, equipamentos e seus tipos, salas, locais, ocorrências e reservas de sala.
                </p>
                <p>
                    <a class="btn btn-primary btn-large" href="#">Abrir documentação</a>
                </p>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-4 column">
            <h2>
                Sobre o CPDS
            </h2>
            <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
            </p>
            <p>
                <a class="btn" href="#">ver mais »</a>
            </p>
        </div>
        <div class="col-md-4 column">
            <h2>
                Equipe
            </h2>
            <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
            </p>
            <p>
                <a class="btn" href="#">ver mais »</a>
            </p>
        </div>
        <div class="col-md-4 column">
            <h2>
                Contato
            </h2>
            <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
            </p>
            <p>
                <a class="btn" href="#">ver mais »</a>
            </p>
        </div>
    </div>
</div>