<?php
foreach($message as $k=>$m):
    $key = key($m);
    $message = current($m);
?>
    <div class="alert alert-<?php echo $key ?>">
        <button type="button" class="close" data-dimiss="alert">&times;</button>
        <strong><?php echo $key == success ? 'Sucesso!' : 'Erro!'?> </strong><?php echo $message?>
    </div>
<?php endforeach; ?>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
                  <br>
                  <img src="/img/logo_cpds.jpg" width="1100" height="320" alt="Logo do CPDS" />
             <h1>
                <br>
               <font color = #0000CC> <b> Bem vindo! </b> </font> 
             </h1>
        </div>
    </div>
</div>
<!--<div class="jumbotron">  ESSA É A DIV QUE DEIXAVA EM VOLTA DA FOTO COR DE CINZA--> 