<div class="panel panel-success">
	<?php
	// module/Album/view/album/album/add.phtml:
	$title = 'Adicionar aluno';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('funcionario', array('action' => 'add')));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
		<?php echo $this->formHidden($form->get('idfuncionario')) ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('nomefuncionario'))."\n"?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('nomefuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('emailfuncionario'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('emailfuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('telefonefuncionario'))."\n" ?>
			<div class="col-lg-10">
				<?php echo $this->formText($form->get('telefonefuncionario')) ?>
			</div>
		</div>
		<div class="form-group">
	    	<div class="col-lg-offset-2 col-lg-10">
				<?php echo $this->formSubmit($form->get('submit')) ?>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>