<div class="panel panel-info">
	<?php
	// module/Album/view/album/album/edit.phtml:
	$title = 'Editar funcionario';
	$this->headTitle($title);
	?>
	<div class="panel-heading">
		<h1><?php echo $this->escapeHtml($title); ?></h1>
	</div>
	<div class="panel-body">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url(
		    'funcionario',
		    array(
		        'action' => 'edit',
		        'id'     => $this->id,
		    )
		));
		$form->prepare();

		echo $this->form()->openTag($form);
		?>
			<?php echo $this->formHidden($form->get('idfuncionario')) ?>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('nomefuncionario'))."\n"?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('nomefuncionario')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('emailfuncionario'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('emailfuncionario')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('telefonefuncionario'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('telefonefuncionario')) ?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('datanasc'))."\n" ?>
				<div class="col-lg-10">
					<?php echo $this->formText($form->get('datanasc')) ?>
				</div>
			<div class="form-group">
		    	<div class="col-lg-offset-2 col-lg-10">
					<?php echo $this->formSubmit($form->get('submit')) ?>
				</div>
			</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script>
jQuery(function($){
   $("#datanasc").mask("99/99/9999");
   $("#telefonefuncionario").mask("(99) 9999-9999");
});
</script>
