<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Funcionário '. $funcionario->getNomefuncionario();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
					<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $funcionario->getNomefuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>E-mail</strong></td>
			    		<td><?php echo $funcionario->getEmailfuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Telefone</strong></td>
			    		<td><?php echo $funcionario->getTelefonefuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Nascimento</strong></td>
			    		<td><?php echo $funcionario->getDatanasc()->format('d/m/Y'); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Admissão</strong></td>
			    		<td><?php echo $funcionario->getDataAdmissao()->format('d/m/Y'); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Grau de Instrução</strong></td>
			    		<td><?php echo $funcionario->getGrauInstrucao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Formação</strong></td>
			    		<td><?php echo $funcionario->getFormacao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Função</strong></td>
			    		<td><?php echo $funcionario->getFuncao(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Horário</strong></td>
			    		<td><?php echo $funcionario->getHorarioInicio() . " às " . $funcionario->getHorarioFim(); ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
		<a class="btn btn-default" href="javascript:history.go(-1)"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
		<a class="btn btn-default" href="<?php echo $this->url('funcionario/default', array('action'=>'relatorioindividual', 'id' => $funcionario->getIdfuncionario()));?>"><span class="glyphicon glyphicon-list-alt"></span> Relatório</a>
	</div>
</div>

