<div class="row">
    
    <div class="col-md-7">
		<div class="panel panel-primary">
			<?php
			// module/Album/view/album/album/delete.phtml:

			$title = 'Funcionario '. $funcionario->getNomefuncionario();
			$this->headTitle($title);
			?>
			<div class="panel-heading">
					<h1><?php echo $this->escapeHtml($title); ?></h1>
				</div>
			<div class="panel-body">
				<table class="table">
					<tr>
			    		<td><strong>Nome</strong></td>
			    		<td><?php echo $funcionario->getNomefuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Email</strong></td>
			    		<td><?php echo $funcionario->getEmailfuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Telefone</strong></td>
			    		<td><?php echo $funcionario->getTelefonefuncionario(); ?></td>
			    	</tr>
			    	<tr>
			    		<td><strong>Data de Nascimento</strong></td>
			    		<td><?php echo $funcionario->getDatanasc()->format('d/m/Y'); ?></td>
			    	</tr>
			  	</table>
			</div>
		</div>
	</div>
</div>

